In [10]:
import pandas as pd

In [11]:
path = "./data/"
#old_base_file = "-citibike-stripdata.csv"
old_base_file = " - Citi Bike trip data.csv"
new_base_file = "-citibike-tripdata.csv"
year_data = "-citi-data.csv"

In [12]:
#it is only the first 2 years of data that has a different name so go ahead and just rename them.

for y in range(2013, 2014, 1):
    for m in range(1, 13, 1):
        if m < 10 :
            m = '0' + str(m)
        file_name = path + str(y) + str(m) + old_base_file
        new_file_name = path + str(y) + str(m) + new_base_file
        print(file_name)
        try:
            df_opened = pd.read_csv(file_name)
            df_opened.to_csv(new_file_name, index = False)
            print("ok")
        except:
            print("error")

./data/201301 - Citi Bike trip data.csv
error
./data/201302 - Citi Bike trip data.csv
error
./data/201303 - Citi Bike trip data.csv
error
./data/201304 - Citi Bike trip data.csv
error
./data/201305 - Citi Bike trip data.csv
error
./data/201306 - Citi Bike trip data.csv
error
./data/201307 - Citi Bike trip data.csv
error
./data/201308 - Citi Bike trip data.csv
ok
./data/201309 - Citi Bike trip data.csv
ok
./data/201310 - Citi Bike trip data.csv
ok
./data/201311 - Citi Bike trip data.csv
ok
./data/201312 - Citi Bike trip data.csv
ok

In [16]:
#lets check the header of each file
dropped_flag = False

for y in range(2013, 2021, 1):
    for m in range(1, 13, 1):
        if m < 10 :
            m = '0' + str(m)
        new_file_name = path + str(y) + str(m) + new_base_file
        print(new_file_name)
        try:
            print('new_file_name', new_file_name)
            df_opened = pd.read_csv(new_file_name, nrows=0)
            print(df_opened)
            print("ok")

        except:
            print("error")

./data/201301-citibike-tripdata.csv
new_file_name ./data/201301-citibike-tripdata.csv
error
./data/201302-citibike-tripdata.csv
new_file_name ./data/201302-citibike-tripdata.csv
error
./data/201303-citibike-tripdata.csv
new_file_name ./data/201303-citibike-tripdata.csv
error
./data/201304-citibike-tripdata.csv
new_file_name ./data/201304-citibike-tripdata.csv
error
./data/201305-citibike-tripdata.csv
new_file_name ./data/201305-citibike-tripdata.csv
error
./data/201306-citibike-tripdata.csv
new_file_name ./data/201306-citibike-tripdata.csv
Empty DataFrame
Columns: [tripduration, starttime, stoptime, start station id, start station name, start station latitude, start station longitude, end station id, end station name, end station latitude, end station longitude, bikeid, usertype, birth year, gender]
Index: []
ok
./data/201307-citibike-tripdata.csv
new_file_name ./data/201307-citibike-tripdata.csv
Empty DataFrame
Columns: [tripduration, starttime, stoptime, start station id, start station name, start station latitude, start station longitude, end station id, end station name, end station latitude, end station longitude, bikeid, usertype, birth year, gender]
Index: []
ok
./data/201308-citibike-tripdata.csv
new_file_name ./data/201308-citibike-tripdata.csv
Empty DataFrame
Columns: [tripduration, starttime, stoptime, start station id, start station name, start station latitude, start station longitude, end station id, end station name, end station latitude, end station longitude, bikeid, usertype, birth year, gender]
Index: []
ok
./data/201309-citibike-tripdata.csv
new_file_name ./data/201309-citibike-tripdata.csv
Empty DataFrame
Columns: [tripduration, starttime, stoptime, start station id, start station name, start station latitude, start station longitude, end station id, end station name, end station latitude, end station longitude, bikeid, usertype, birth year, gender]
Index: []
ok
./data/201310-citibike-tripdata.csv
new_file_name ./data/201310-citibike-tripdata.csv
Empty DataFrame
Columns: [tripduration, starttime, stoptime, start station id, start station name, start station latitude, start station longitude, end station id, end station name, end station latitude, end station longitude, bikeid, usertype, birth year, gender]
Index: []
ok
./data/201311-citibike-tripdata.csv
new_file_name ./data/201311-citibike-tripdata.csv
Empty DataFrame
Columns: [tripduration, starttime, stoptime, start station id, start station name, start station latitude, start station longitude, end station id, end station name, end station latitude, end station longitude, bikeid, usertype, birth year, gender]
Index: []
ok
./data/201312-citibike-tripdata.csv
new_file_name ./data/201312-citibike-tripdata.csv
Empty DataFrame
Columns: [tripduration, starttime, stoptime, start station id, start station name, start station latitude, start station longitude, end station id, end station name, end station latitude, end station longitude, bikeid, usertype, birth year, gender]
Index: []
ok
./data/201401-citibike-tripdata.csv
new_file_name ./data/201401-citibike-tripdata.csv
Empty DataFrame
Columns: [tripduration, starttime, stoptime, start station id, start station name, start station latitude, start station longitude, end station id, end station name, end station latitude, end station longitude, bikeid, usertype, birth year, gender]
Index: []
ok
./data/201402-citibike-tripdata.csv
new_file_name ./data/201402-citibike-tripdata.csv
Empty DataFrame
Columns: [tripduration, starttime, stoptime, start station id, start station name, start station latitude, start station longitude, end station id, end station name, end station latitude, end station longitude, bikeid, usertype, birth year, gender]
Index: []
ok
./data/201403-citibike-tripdata.csv
new_file_name ./data/201403-citibike-tripdata.csv
Empty DataFrame
Columns: [tripduration, starttime, stoptime, start station id, start station name, start station latitude, start station longitude, end station id, end station name, end station latitude, end station longitude, bikeid, usertype, birth year, gender]
Index: []
ok
./data/201404-citibike-tripdata.csv
new_file_name ./data/201404-citibike-tripdata.csv
Empty DataFrame
Columns: [tripduration, starttime, stoptime, start station id, start station name, start station latitude, start station longitude, end station id, end station name, end station latitude, end station longitude, bikeid, usertype, birth year, gender]
Index: []
ok
./data/201405-citibike-tripdata.csv
new_file_name ./data/201405-citibike-tripdata.csv
Empty DataFrame
Columns: [tripduration, starttime, stoptime, start station id, start station name, start station latitude, start station longitude, end station id, end station name, end station latitude, end station longitude, bikeid, usertype, birth year, gender]
Index: []
ok
./data/201406-citibike-tripdata.csv
new_file_name ./data/201406-citibike-tripdata.csv
Empty DataFrame
Columns: [tripduration, starttime, stoptime, start station id, start station name, start station latitude, start station longitude, end station id, end station name, end station latitude, end station longitude, bikeid, usertype, birth year, gender]
Index: []
ok
./data/201407-citibike-tripdata.csv
new_file_name ./data/201407-citibike-tripdata.csv
Empty DataFrame
Columns: [tripduration, starttime, stoptime, start station id, start station name, start station latitude, start station longitude, end station id, end station name, end station latitude, end station longitude, bikeid, usertype, birth year, gender]
Index: []
ok
./data/201408-citibike-tripdata.csv
new_file_name ./data/201408-citibike-tripdata.csv
Empty DataFrame
Columns: [tripduration, starttime, stoptime, start station id, start station name, start station latitude, start station longitude, end station id, end station name, end station latitude, end station longitude, bikeid, usertype, birth year, gender]
Index: []
ok
./data/201409-citibike-tripdata.csv
new_file_name ./data/201409-citibike-tripdata.csv
Empty DataFrame
Columns: [tripduration, starttime, stoptime, start station id, start station name, start station latitude, start station longitude, end station id, end station name, end station latitude, end station longitude, bikeid, usertype, birth year, gender]
Index: []
ok
./data/201410-citibike-tripdata.csv
new_file_name ./data/201410-citibike-tripdata.csv
Empty DataFrame
Columns: [tripduration, starttime, stoptime, start station id, start station name, start station latitude, start station longitude, end station id, end station name, end station latitude, end station longitude, bikeid, usertype, birth year, gender]
Index: []
ok
./data/201411-citibike-tripdata.csv
new_file_name ./data/201411-citibike-tripdata.csv
Empty DataFrame
Columns: [tripduration, starttime, stoptime, start station id, start station name, start station latitude, start station longitude, end station id, end station name, end station latitude, end station longitude, bikeid, usertype, birth year, gender]
Index: []
ok
./data/201412-citibike-tripdata.csv
new_file_name ./data/201412-citibike-tripdata.csv
Empty DataFrame
Columns: [tripduration, starttime, stoptime, start station id, start station name, start station latitude, start station longitude, end station id, end station name, end station latitude, end station longitude, bikeid, usertype, birth year, gender]
Index: []
ok
./data/201501-citibike-tripdata.csv
new_file_name ./data/201501-citibike-tripdata.csv
Empty DataFrame
Columns: [tripduration, starttime, stoptime, start station id, start station name, start station latitude, start station longitude, end station id, end station name, end station latitude, end station longitude, bikeid, usertype, birth year, gender]
Index: []
ok
./data/201502-citibike-tripdata.csv
new_file_name ./data/201502-citibike-tripdata.csv
Empty DataFrame
Columns: [tripduration, starttime, stoptime, start station id, start station name, start station latitude, start station longitude, end station id, end station name, end station latitude, end station longitude, bikeid, usertype, birth year, gender]
Index: []
ok
./data/201503-citibike-tripdata.csv
new_file_name ./data/201503-citibike-tripdata.csv
Empty DataFrame
Columns: [tripduration, starttime, stoptime, start station id, start station name, start station latitude, start station longitude, end station id, end station name, end station latitude, end station longitude, bikeid, usertype, birth year, gender]
Index: []
ok
./data/201504-citibike-tripdata.csv
new_file_name ./data/201504-citibike-tripdata.csv
Empty DataFrame
Columns: [tripduration, starttime, stoptime, start station id, start station name, start station latitude, start station longitude, end station id, end station name, end station latitude, end station longitude, bikeid, usertype, birth year, gender]
Index: []
ok
./data/201505-citibike-tripdata.csv
new_file_name ./data/201505-citibike-tripdata.csv
Empty DataFrame
Columns: [tripduration, starttime, stoptime, start station id, start station name, start station latitude, start station longitude, end station id, end station name, end station latitude, end station longitude, bikeid, usertype, birth year, gender]
Index: []
ok
./data/201506-citibike-tripdata.csv
new_file_name ./data/201506-citibike-tripdata.csv
Empty DataFrame
Columns: [tripduration, starttime, stoptime, start station id, start station name, start station latitude, start station longitude, end station id, end station name, end station latitude, end station longitude, bikeid, usertype, birth year, gender]
Index: []
ok
./data/201507-citibike-tripdata.csv
new_file_name ./data/201507-citibike-tripdata.csv
Empty DataFrame
Columns: [tripduration, starttime, stoptime, start station id, start station name, start station latitude, start station longitude, end station id, end station name, end station latitude, end station longitude, bikeid, usertype, birth year, gender]
Index: []
ok
./data/201508-citibike-tripdata.csv
new_file_name ./data/201508-citibike-tripdata.csv
Empty DataFrame
Columns: [tripduration, starttime, stoptime, start station id, start station name, start station latitude, start station longitude, end station id, end station name, end station latitude, end station longitude, bikeid, usertype, birth year, gender]
Index: []
ok
./data/201509-citibike-tripdata.csv
new_file_name ./data/201509-citibike-tripdata.csv
Empty DataFrame
Columns: [tripduration, starttime, stoptime, start station id, start station name, start station latitude, start station longitude, end station id, end station name, end station latitude, end station longitude, bikeid, usertype, birth year, gender]
Index: []
ok
./data/201510-citibike-tripdata.csv
new_file_name ./data/201510-citibike-tripdata.csv
Empty DataFrame
Columns: [tripduration, starttime, stoptime, start station id, start station name, start station latitude, start station longitude, end station id, end station name, end station latitude, end station longitude, bikeid, usertype, birth year, gender]
Index: []
ok
./data/201511-citibike-tripdata.csv
new_file_name ./data/201511-citibike-tripdata.csv
Empty DataFrame
Columns: [tripduration, starttime, stoptime, start station id, start station name, start station latitude, start station longitude, end station id, end station name, end station latitude, end station longitude, bikeid, usertype, birth year, gender]
Index: []
ok
./data/201512-citibike-tripdata.csv
new_file_name ./data/201512-citibike-tripdata.csv
Empty DataFrame
Columns: [tripduration, starttime, stoptime, start station id, start station name, start station latitude, start station longitude, end station id, end station name, end station latitude, end station longitude, bikeid, usertype, birth year, gender]
Index: []
ok
./data/201601-citibike-tripdata.csv
new_file_name ./data/201601-citibike-tripdata.csv
Empty DataFrame
Columns: [tripduration, starttime, stoptime, start station id, start station name, start station latitude, start station longitude, end station id, end station name, end station latitude, end station longitude, bikeid, usertype, birth year, gender]

Index: []
ok
./data/201602-citibike-tripdata.csv
new_file_name ./data/201602-citibike-tripdata.csv
Empty DataFrame
Columns: [tripduration, starttime, stoptime, start station id, start station name, start station latitude, start station longitude, end station id, end station name, end station latitude, end station longitude, bikeid, usertype, birth year, gender]
Index: []
ok
./data/201603-citibike-tripdata.csv
new_file_name ./data/201603-citibike-tripdata.csv
Empty DataFrame
Columns: [tripduration, starttime, stoptime, start station id, start station name, start station latitude, start station longitude, end station id, end station name, end station latitude, end station longitude, bikeid, usertype, birth year, gender]
Index: []
ok
./data/201604-citibike-tripdata.csv
new_file_name ./data/201604-citibike-tripdata.csv
Empty DataFrame
Columns: [tripduration, starttime, stoptime, start station id, start station name, start station latitude, start station longitude, end station id, end station name, end station latitude, end station longitude, bikeid, usertype, birth year, gender]
Index: []
ok
./data/201605-citibike-tripdata.csv
new_file_name ./data/201605-citibike-tripdata.csv
Empty DataFrame
Columns: [tripduration, starttime, stoptime, start station id, start station name, start station latitude, start station longitude, end station id, end station name, end station latitude, end station longitude, bikeid, usertype, birth year, gender]
Index: []
ok
./data/201606-citibike-tripdata.csv
new_file_name ./data/201606-citibike-tripdata.csv
Empty DataFrame
Columns: [tripduration, starttime, stoptime, start station id, start station name, start station latitude, start station longitude, end station id, end station name, end station latitude, end station longitude, bikeid, usertype, birth year, gender]
Index: []
ok
./data/201607-citibike-tripdata.csv
new_file_name ./data/201607-citibike-tripdata.csv
Empty DataFrame
Columns: [tripduration, starttime, stoptime, start station id, start station name, start station latitude, start station longitude, end station id, end station name, end station latitude, end station longitude, bikeid, usertype, birth year, gender]
Index: []
ok
./data/201608-citibike-tripdata.csv
new_file_name ./data/201608-citibike-tripdata.csv
Empty DataFrame
Columns: [tripduration, starttime, stoptime, start station id, start station name, start station latitude, start station longitude, end station id, end station name, end station latitude, end station longitude, bikeid, usertype, birth year, gender]
Index: []
ok
./data/201609-citibike-tripdata.csv
new_file_name ./data/201609-citibike-tripdata.csv
Empty DataFrame
Columns: [tripduration, starttime, stoptime, start station id, start station name, start station latitude, start station longitude, end station id, end station name, end station latitude, end station longitude, bikeid, usertype, birth year, gender]
Index: []
ok
./data/201610-citibike-tripdata.csv
new_file_name ./data/201610-citibike-tripdata.csv
Empty DataFrame
Columns: [Trip Duration, Start Time, Stop Time, Start Station ID, Start Station Name, Start Station Latitude, Start Station Longitude, End Station ID, End Station Name, End Station Latitude, End Station Longitude, Bike ID, User Type, Birth Year, Gender]
Index: []
ok
./data/201611-citibike-tripdata.csv
new_file_name ./data/201611-citibike-tripdata.csv
Empty DataFrame
Columns: [Trip Duration, Start Time, Stop Time, Start Station ID, Start Station Name, Start Station Latitude, Start Station Longitude, End Station ID, End Station Name, End Station Latitude, End Station Longitude, Bike ID, User Type, Birth Year, Gender]
Index: []
ok
./data/201612-citibike-tripdata.csv
new_file_name ./data/201612-citibike-tripdata.csv
Empty DataFrame
Columns: [Trip Duration, Start Time, Stop Time, Start Station ID, Start Station Name, Start Station Latitude, Start Station Longitude, End Station ID, End Station Name, End Station Latitude, End Station Longitude, Bike ID, User Type, Birth Year, Gender]
Index: []
ok
./data/201701-citibike-tripdata.csv
new_file_name ./data/201701-citibike-tripdata.csv
Empty DataFrame
Columns: [Trip Duration, Start Time, Stop Time, Start Station ID, Start Station Name, Start Station Latitude, Start Station Longitude, End Station ID, End Station Name, End Station Latitude, End Station Longitude, Bike ID, User Type, Birth Year, Gender]
Index: []
ok
./data/201702-citibike-tripdata.csv
new_file_name ./data/201702-citibike-tripdata.csv
Empty DataFrame
Columns: [Trip Duration, Start Time, Stop Time, Start Station ID, Start Station Name, Start Station Latitude, Start Station Longitude, End Station ID, End Station Name, End Station Latitude, End Station Longitude, Bike ID, User Type, Birth Year, Gender]
Index: []
ok
./data/201703-citibike-tripdata.csv
new_file_name ./data/201703-citibike-tripdata.csv
Empty DataFrame
Columns: [Trip Duration, Start Time, Stop Time, Start Station ID, Start Station Name, Start Station Latitude, Start Station Longitude, End Station ID, End Station Name, End Station Latitude, End Station Longitude, Bike ID, User Type, Birth Year, Gender]
Index: []
ok
./data/201704-citibike-tripdata.csv
new_file_name ./data/201704-citibike-tripdata.csv
Empty DataFrame
Columns: [tripduration, starttime, stoptime, start station id, start station name, start station latitude, start station longitude, end station id, end station name, end station latitude, end station longitude, bikeid, usertype, birth year, gender]
Index: []
ok
./data/201705-citibike-tripdata.csv
new_file_name ./data/201705-citibike-tripdata.csv
Empty DataFrame
Columns: [tripduration, starttime, stoptime, start station id, start station name, start station latitude, start station longitude, end station id, end station name, end station latitude, end station longitude, bikeid, usertype, birth year, gender]
Index: []
ok
./data/201706-citibike-tripdata.csv
new_file_name ./data/201706-citibike-tripdata.csv
Empty DataFrame
Columns: [tripduration, starttime, stoptime, start station id, start station name, start station latitude, start station longitude, end station id, end station name, end station latitude, end station longitude, bikeid, usertype, birth year, gender]
Index: []
ok
./data/201707-citibike-tripdata.csv
new_file_name ./data/201707-citibike-tripdata.csv
Empty DataFrame
Columns: [tripduration, starttime, stoptime, start station id, start station name, start station latitude, start station longitude, end station id, end station name, end station latitude, end station longitude, bikeid, usertype, birth year, gender]
Index: []
ok
./data/201708-citibike-tripdata.csv
new_file_name ./data/201708-citibike-tripdata.csv
Empty DataFrame
Columns: [tripduration, starttime, stoptime, start station id, start station name, start station latitude, start station longitude, end station id, end station name, end station latitude, end station longitude, bikeid, usertype, birth year, gender]
Index: []
ok
./data/201709-citibike-tripdata.csv
new_file_name ./data/201709-citibike-tripdata.csv
Empty DataFrame
Columns: [tripduration, starttime, stoptime, start station id, start station name, start station latitude, start station longitude, end station id, end station name, end station latitude, end station longitude, bikeid, usertype, birth year, gender]
Index: []
ok
./data/201710-citibike-tripdata.csv
new_file_name ./data/201710-citibike-tripdata.csv
Empty DataFrame
Columns: [tripduration, starttime, stoptime, start station id, start station name, start station latitude, start station longitude, end station id, end station name, end station latitude, end station longitude, bikeid, usertype, birth year, gender]
Index: []
ok
./data/201711-citibike-tripdata.csv
new_file_name ./data/201711-citibike-tripdata.csv
Empty DataFrame
Columns: [tripduration, starttime, stoptime, start station id, start station name, start station latitude, start station longitude, end station id, end station name, end station latitude, end station longitude, bikeid, usertype, birth year, gender]
Index: []
ok
./data/201712-citibike-tripdata.csv
new_file_name ./data/201712-citibike-tripdata.csv
Empty DataFrame
Columns: [tripduration, starttime, stoptime, start station id, start station name, start station latitude, start station longitude, end station id, end station name, end station latitude, end station longitude, bikeid, usertype, birth year, gender]
Index: []
ok
./data/201801-citibike-tripdata.csv
new_file_name ./data/201801-citibike-tripdata.csv
Empty DataFrame
Columns: [tripduration, starttime, stoptime, start station id, start station name, start station latitude, start station longitude, end station id, end station name, end station latitude, end station longitude, bikeid, usertype, birth year, gender]
Index: []
ok
./data/201802-citibike-tripdata.csv
new_file_name ./data/201802-citibike-tripdata.csv
Empty DataFrame
Columns: [tripduration, starttime, stoptime, start station id, start station name, start station latitude, start station longitude, end station id, end station name, end station latitude, end station longitude, bikeid, usertype, birth year, gender]
Index: []
ok
./data/201803-citibike-tripdata.csv
new_file_name ./data/201803-citibike-tripdata.csv
Empty DataFrame
Columns: [tripduration, starttime, stoptime, start station id, start station name, start station latitude, start station longitude, end station id, end station name, end station latitude, end station longitude, bikeid, usertype, birth year, gender]
Index: []
ok
./data/201804-citibike-tripdata.csv
new_file_name ./data/201804-citibike-tripdata.csv
Empty DataFrame
Columns: [tripduration, starttime, stoptime, start station id, start station name, start station latitude, start station longitude, end station id, end station name, end station latitude, end station longitude, bikeid, usertype, birth year, gender]
Index: []
ok
./data/201805-citibike-tripdata.csv
new_file_name ./data/201805-citibike-tripdata.csv
Empty DataFrame
Columns: [tripduration, starttime, stoptime, start station id, start station name, start station latitude, start station longitude, end station id, end station name, end station latitude, end station longitude, bikeid, usertype, birth year, gender]
Index: []
ok
./data/201806-citibike-tripdata.csv
new_file_name ./data/201806-citibike-tripdata.csv
Empty DataFrame
Columns: [tripduration, starttime, stoptime, start station id, start station name, start station latitude, start station longitude, end station id, end station name, end station latitude, end station longitude, bikeid, usertype, birth year, gender]
Index: []
ok
./data/201807-citibike-tripdata.csv
new_file_name ./data/201807-citibike-tripdata.csv
Empty DataFrame
Columns: [tripduration, starttime, stoptime, start station id, start station name, start station latitude, start station longitude, end station id, end station name, end station latitude, end station longitude, bikeid, usertype, birth year, gender]
Index: []
ok
./data/201808-citibike-tripdata.csv
new_file_name ./data/201808-citibike-tripdata.csv
Empty DataFrame
Columns: [tripduration, starttime, stoptime, start station id, start station name, start station latitude, start station longitude, end station id, end station name, end station latitude, end station longitude, bikeid, usertype, birth year, gender]
Index: []
ok
./data/201809-citibike-tripdata.csv
new_file_name ./data/201809-citibike-tripdata.csv
Empty DataFrame
Columns: [tripduration, starttime, stoptime, start station id, start station name, start station latitude, start station longitude, end station id, end station name, end station latitude, end station longitude, bikeid, usertype, birth year, gender]
Index: []
ok
./data/201810-citibike-tripdata.csv
new_file_name ./data/201810-citibike-tripdata.csv
Empty DataFrame
Columns: [tripduration, starttime, stoptime, start station id, start station name, start station latitude, start station longitude, end station id, end station name, end station latitude, end station longitude, bikeid, usertype, birth year, gender]
Index: []
ok
./data/201811-citibike-tripdata.csv
new_file_name ./data/201811-citibike-tripdata.csv
Empty DataFrame
Columns: [tripduration, starttime, stoptime, start station id, start station name, start station latitude, start station longitude, end station id, end station name, end station latitude, end station longitude, bikeid, usertype, birth year, gender]
Index: []
ok
./data/201812-citibike-tripdata.csv
new_file_name ./data/201812-citibike-tripdata.csv
Empty DataFrame
Columns: [tripduration, starttime, stoptime, start station id, start station name, start station latitude, start station longitude, end station id, end station name, end station latitude, end station longitude, bikeid, usertype, birth year, gender]
Index: []
ok
./data/201901-citibike-tripdata.csv
new_file_name ./data/201901-citibike-tripdata.csv
Empty DataFrame
Columns: [tripduration, starttime, stoptime, start station id, start station name, start station latitude, start station longitude, end station id, end station name, end station latitude, end station longitude, bikeid, usertype, birth year, gender]
Index: []
ok
./data/201902-citibike-tripdata.csv

new_file_name ./data/201902-citibike-tripdata.csv
Empty DataFrame
Columns: [tripduration, starttime, stoptime, start station id, start station name, start station latitude, start station longitude, end station id, end station name, end station latitude, end station longitude, bikeid, usertype, birth year, gender]
Index: []
ok
./data/201903-citibike-tripdata.csv
new_file_name ./data/201903-citibike-tripdata.csv
Empty DataFrame
Columns: [tripduration, starttime, stoptime, start station id, start station name, start station latitude, start station longitude, end station id, end station name, end station latitude, end station longitude, bikeid, usertype, birth year, gender]
Index: []
ok
./data/201904-citibike-tripdata.csv
new_file_name ./data/201904-citibike-tripdata.csv
Empty DataFrame
Columns: [tripduration, starttime, stoptime, start station id, start station name, start station latitude, start station longitude, end station id, end station name, end station latitude, end station longitude, bikeid, usertype, birth year, gender]
Index: []
ok
./data/201905-citibike-tripdata.csv
new_file_name ./data/201905-citibike-tripdata.csv
Empty DataFrame
Columns: [tripduration, starttime, stoptime, start station id, start station name, start station latitude, start station longitude, end station id, end station name, end station latitude, end station longitude, bikeid, usertype, birth year, gender]
Index: []
ok
./data/201906-citibike-tripdata.csv
new_file_name ./data/201906-citibike-tripdata.csv
Empty DataFrame
Columns: [tripduration, starttime, stoptime, start station id, start station name, start station latitude, start station longitude, end station id, end station name, end station latitude, end station longitude, bikeid, usertype, birth year, gender]
Index: []
ok
./data/201907-citibike-tripdata.csv
new_file_name ./data/201907-citibike-tripdata.csv
Empty DataFrame
Columns: [tripduration, starttime, stoptime, start station id, start station name, start station latitude, start station longitude, end station id, end station name, end station latitude, end station longitude, bikeid, usertype, birth year, gender]
Index: []
ok
./data/201908-citibike-tripdata.csv
new_file_name ./data/201908-citibike-tripdata.csv
Empty DataFrame
Columns: [tripduration, starttime, stoptime, start station id, start station name, start station latitude, start station longitude, end station id, end station name, end station latitude, end station longitude, bikeid, usertype, birth year, gender]
Index: []
ok
./data/201909-citibike-tripdata.csv
new_file_name ./data/201909-citibike-tripdata.csv
Empty DataFrame
Columns: [tripduration, starttime, stoptime, start station id, start station name, start station latitude, start station longitude, end station id, end station name, end station latitude, end station longitude, bikeid, usertype, birth year, gender]
Index: []
ok
./data/201910-citibike-tripdata.csv
new_file_name ./data/201910-citibike-tripdata.csv
Empty DataFrame
Columns: [tripduration, starttime, stoptime, start station id, start station name, start station latitude, start station longitude, end station id, end station name, end station latitude, end station longitude, bikeid, usertype, birth year, gender]
Index: []
ok
./data/201911-citibike-tripdata.csv
new_file_name ./data/201911-citibike-tripdata.csv
Empty DataFrame
Columns: [tripduration, starttime, stoptime, start station id, start station name, start station latitude, start station longitude, end station id, end station name, end station latitude, end station longitude, bikeid, usertype, birth year, gender]
Index: []
ok
./data/201912-citibike-tripdata.csv
new_file_name ./data/201912-citibike-tripdata.csv
Empty DataFrame
Columns: [tripduration, starttime, stoptime, start station id, start station name, start station latitude, start station longitude, end station id, end station name, end station latitude, end station longitude, bikeid, usertype, birth year, gender]
Index: []
ok
./data/202001-citibike-tripdata.csv
new_file_name ./data/202001-citibike-tripdata.csv
Empty DataFrame
Columns: [tripduration, starttime, stoptime, start station id, start station name, start station latitude, start station longitude, end station id, end station name, end station latitude, end station longitude, bikeid, usertype, birth year, gender]
Index: []
ok
./data/202002-citibike-tripdata.csv
new_file_name ./data/202002-citibike-tripdata.csv
Empty DataFrame
Columns: [tripduration, starttime, stoptime, start station id, start station name, start station latitude, start station longitude, end station id, end station name, end station latitude, end station longitude, bikeid, usertype, birth year, gender]
Index: []
ok
./data/202003-citibike-tripdata.csv
new_file_name ./data/202003-citibike-tripdata.csv
Empty DataFrame
Columns: [tripduration, starttime, stoptime, start station id, start station name, start station latitude, start station longitude, end station id, end station name, end station latitude, end station longitude, bikeid, usertype, birth year, gender]
Index: []
ok
./data/202004-citibike-tripdata.csv
new_file_name ./data/202004-citibike-tripdata.csv
Empty DataFrame
Columns: [tripduration, starttime, stoptime, start station id, start station name, start station latitude, start station longitude, end station id, end station name, end station latitude, end station longitude, bikeid, usertype, birth year, gender]
Index: []
ok
./data/202005-citibike-tripdata.csv
new_file_name ./data/202005-citibike-tripdata.csv
Empty DataFrame
Columns: [tripduration, starttime, stoptime, start station id, start station name, start station latitude, start station longitude, end station id, end station name, end station latitude, end station longitude, bikeid, usertype, birth year, gender]
Index: []
ok
./data/202006-citibike-tripdata.csv
new_file_name ./data/202006-citibike-tripdata.csv
Empty DataFrame
Columns: [tripduration, starttime, stoptime, start station id, start station name, start station latitude, start station longitude, end station id, end station name, end station latitude, end station longitude, bikeid, usertype, birth year, gender]
Index: []
ok
./data/202007-citibike-tripdata.csv
new_file_name ./data/202007-citibike-tripdata.csv
Empty DataFrame
Columns: [tripduration, starttime, stoptime, start station id, start station name, start station latitude, start station longitude, end station id, end station name, end station latitude, end station longitude, bikeid, usertype, birth year, gender]
Index: []
ok
./data/202008-citibike-tripdata.csv
new_file_name ./data/202008-citibike-tripdata.csv
Empty DataFrame
Columns: [tripduration, starttime, stoptime, start station id, start station name, start station latitude, start station longitude, end station id, end station name, end station latitude, end station longitude, bikeid, usertype, birth year, gender]
Index: []
ok
./data/202009-citibike-tripdata.csv
new_file_name ./data/202009-citibike-tripdata.csv
error
./data/202010-citibike-tripdata.csv
new_file_name ./data/202010-citibike-tripdata.csv
error
./data/202011-citibike-tripdata.csv
new_file_name ./data/202011-citibike-tripdata.csv
error
./data/202012-citibike-tripdata.csv
new_file_name ./data/202012-citibike-tripdata.csv
error

In [33]:
#make a file of one year

for y in range(2013, 2014, 1):
    year_df = pd.DataFrame()
    for m in range(1, 13, 1):
        print('month', m)
        if m < 10 :
            m = '0' + str(m)
        new_file_name = path + str(y) + str(m) + new_base_file
        print(new_file_name)
        try:
            print('new_file_name', new_file_name)
            #index_col = 0 to not add an index, index_col = False assigns an index.
            df_opened = pd.read_csv(new_file_name, index_col = 0)
            print(df_opened)
            print("ok")
            year_df = year_df.append(df_opened)
        except:
            print("error")
    print('writing file')
    year_df.to_csv(path + str(y) + year_data, index = False)

month 1
./data/201301-citibike-tripdata.csv
new_file_name ./data/201301-citibike-tripdata.csv
error
month 2
./data/201302-citibike-tripdata.csv
new_file_name ./data/201302-citibike-tripdata.csv
error
month 3
./data/201303-citibike-tripdata.csv
new_file_name ./data/201303-citibike-tripdata.csv
error
month 4
./data/201304-citibike-tripdata.csv
new_file_name ./data/201304-citibike-tripdata.csv
error
month 5
./data/201305-citibike-tripdata.csv
new_file_name ./data/201305-citibike-tripdata.csv
error
month 6
./data/201306-citibike-tripdata.csv
new_file_name ./data/201306-citibike-tripdata.csv
                        starttime             stoptime  start station id  \
tripduration
695           2013-06-01 00:00:01  2013-06-01 00:11:36               444
693           2013-06-01 00:00:08  2013-06-01 00:11:41               444
2059          2013-06-01 00:00:44  2013-06-01 00:35:03               406
123           2013-06-01 00:01:04  2013-06-01 00:03:07               475
1521          2013-06-01 00:01:22  2013-06-01 00:26:43              2008
...                           ...                  ...               ...
925           2013-06-30 23:59:27  2013-07-01 00:14:52               509
279           2013-06-30 23:59:36  2013-07-01 00:04:15               116
161           2013-06-30 23:59:33  2013-07-01 00:02:14               443
909           2013-06-30 23:59:47  2013-07-01 00:14:56               509
634           2013-07-01 00:00:00  2013-07-01 00:10:34               164

                  start station name  start station latitude  \
tripduration
695               Broadway & W 24 St               40.742354
693               Broadway & W 24 St               40.742354
2059          Hicks St & Montague St               40.695128
123              E 15 St & Irving Pl               40.735243
1521           Little West St & 1 Pl               40.705693
...                              ...                     ...
925                  9 Ave & W 22 St               40.745497
279                  W 17 St & 8 Ave               40.741776
161             Bedford Ave & S 9 St               40.708531
909                  9 Ave & W 22 St               40.745497
634                  E 47 St & 2 Ave               40.753231

              start station longitude  end station id        end station name  \
tripduration
695                        -73.989151           434.0         9 Ave & W 18 St
693                        -73.989151           434.0         9 Ave & W 18 St
2059                       -73.995951           406.0  Hicks St & Montague St
123                        -73.987586           262.0         Washington Park
1521                       -74.016777           310.0     State St & Smith St
...                               ...             ...                     ...
925                        -74.001971           462.0        W 22 St & 10 Ave
279                        -74.001497           494.0         W 26 St & 8 Ave
161                        -73.964090           282.0      Kent Ave & S 11 St
909                        -74.001971           462.0        W 22 St & 10 Ave
634                        -73.970325           504.0         1 Ave & E 16 St

              end station latitude  end station longitude  bikeid    usertype  \
tripduration
695                      40.743174             -74.003664   19678  Subscriber
693                      40.743174             -74.003664   16649  Subscriber
2059                     40.695128             -73.995951   19599    Customer
123                      40.691782             -73.973730   16352  Subscriber
1521                     40.689269             -73.989129   15567  Subscriber
...                            ...                    ...     ...         ...
925                      40.746920             -74.004519   15250  Subscriber
279                      40.747348             -73.997236   19411    Customer
161                      40.707645             -73.968415   18910  Subscriber
909                      40.746920             -74.004519   16108    Customer
634                      40.732219             -73.981656   16950    Customer

              birth year  gender
tripduration
695               1983.0       1
693               1984.0       1
2059                 NaN       0
123               1960.0       1
1521              1983.0       1
...                  ...     ...
925               1964.0       1
279                  NaN       0
161               1972.0       2
909                  NaN       0
634                  NaN       0

[577703 rows x 14 columns]
ok
month 7
./data/201307-citibike-tripdata.csv
new_file_name ./data/201307-citibike-tripdata.csv
                    starttime       stoptime  start station id  \
tripduration
634             7/1/2013 0:00  7/1/2013 0:10               164
1547            7/1/2013 0:00  7/1/2013 0:25               388
178             7/1/2013 0:01  7/1/2013 0:04               293
1580            7/1/2013 0:01  7/1/2013 0:27               531
757             7/1/2013 0:01  7/1/2013 0:13               382
...                       ...            ...               ...
1493          7/31/2013 23:59  8/1/2013 0:24               285
417           7/31/2013 23:59  8/1/2013 0:06               460
903           7/31/2013 23:59  8/1/2013 0:14               146
455           7/31/2013 23:59  8/1/2013 0:07               324
875           7/31/2013 23:59  8/1/2013 0:14               146

                   start station name  start station latitude  \
tripduration
634                   E 47 St & 2 Ave               40.753231
1547                 W 26 St & 10 Ave               40.749718
178             Lafayette St & E 8 St               40.730287
1580           Forsyth St & Broome St               40.718939
757           University Pl & E 14 St               40.734927
...                               ...                     ...
1493               Broadway & E 14 St               40.734546
417                S 4 St & Wythe Ave               40.712859
903              Hudson St & Reade St               40.716250
455           DeKalb Ave & Hudson Ave               40.689888
875              Hudson St & Reade St               40.716250

              start station longitude  end station id  \
tripduration
634                        -73.970325             504
1547                       -74.002950             459
178                        -73.990765             237
1580                       -73.992663             499
757                        -73.992005             410
...                               ...             ...
1493                       -73.990741             305
417                        -73.965903            2002
903                        -74.009106             342
455                        -73.981013             366
875                        -74.009106             342

                          end station name  end station latitude  \
tripduration
634                        1 Ave & E 15 St             40.732219
1547                      W 20 St & 11 Ave             40.746745
178                        E 11 St & 2 Ave             40.730473
1580                    Broadway & W 60 St             40.769155
757                Suffolk St & Stanton St             40.720664
...                                    ...                   ...
1493                       E 58 St & 3 Ave             40.760958
417           Wythe Ave & Metropolitan Ave             40.716887
903             Columbia St & Rivington St             40.717400
455               Clinton Ave & Myrtle Ave             40.693261
875             Columbia St & Rivington St             40.717400

              end station longitude  bikeid    usertype birth year  gender
tripduration
634                      -73.981656   16950    Customer         \N       0
1547                     -74.007756   19816    Customer         \N       0
178                      -73.986724   14548  Subscriber       1980       2
1580                     -73.981918   16063    Customer         \N       0
757                      -73.985180   19213  Subscriber       1986       1
...                             ...     ...         ...        ...     ...
1493                     -73.967245   16279    Customer         \N       0
417                      -73.963198   15287    Customer         \N       0
903                      -73.980166   18213  Subscriber       1963       1
455                      -73.968896   15085  Subscriber       1981       1
875                      -73.980166   19333  Subscriber       1964       1

[843416 rows x 14 columns]
ok

month 8
./data/201308-citibike-tripdata.csv
new_file_name ./data/201308-citibike-tripdata.csv

C:\Users\thead\anaconda3\lib\site-packages\numpy\lib\arraysetops.py:569: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)

                        starttime             stoptime  start station id  \
tripduration
664           2013-08-01 00:00:00  2013-08-01 00:11:04               449
2115          2013-08-01 00:00:01  2013-08-01 00:35:16               254
385           2013-08-01 00:00:03  2013-08-01 00:06:28               460
653           2013-08-01 00:00:10  2013-08-01 00:11:03               398
954           2013-08-01 00:00:11  2013-08-01 00:16:05               319
...                           ...                  ...               ...
1016          2013-08-31 23:59:36  2013-09-01 00:16:32               454
579           2013-08-31 23:59:41  2013-09-01 00:09:20               236
971           2013-08-31 23:59:42  2013-09-01 00:15:53               534
1766          2013-08-31 23:59:43  2013-09-01 00:29:09               525
484           2013-08-31 23:59:49  2013-09-01 00:07:53               504

                    start station name  start station latitude  \
tripduration
664                    W 52 St & 9 Ave               40.764618
2115                   W 11 St & 6 Ave               40.735324
385                 S 4 St & Wythe Ave               40.712859
653           Atlantic Ave & Furman St               40.691652
954                Park Pl & Church St               40.713361
...                                ...                     ...
1016                   E 51 St & 1 Ave               40.754557
579                St Marks Pl & 2 Ave               40.728419
971            Water - Whitehall Plaza               40.702551
1766                  W 34 St & 11 Ave               40.755942
484                    1 Ave & E 15 St               40.732219

              start station longitude  end station id  \
tripduration
664                        -73.987895             479
2115                       -73.998004             195
385                        -73.965903            2002
653                        -73.999979             398
954                        -74.009376             336
...                               ...             ...
1016                       -73.965930            2003
579                        -73.987140             311
971                        -74.012723             361
1766                       -74.002116            2008
484                        -73.981656             474

                          end station name  end station latitude  \
tripduration
664                        9 Ave & W 45 St             40.760193
2115                 Liberty St & Broadway             40.709056
385           Wythe Ave & Metropolitan Ave             40.716887
653               Atlantic Ave & Furman St             40.691652
954            Sullivan St & Washington Sq             40.730477
...                                    ...                   ...
1016                       1 Ave & E 18 St             40.734161
579                 Norfolk St & Broome St             40.717227
971                   Allen St & Hester St             40.716059
1766                 Little West St & 1 Pl             40.705693
484                        5 Ave & E 29 St             40.745168

              end station longitude  bikeid    usertype birth year  gender
tripduration
664                      -73.991255   20068  Subscriber       1944       1
2115                     -74.010434   17095  Subscriber       1974       1
385                      -73.963198   18197    Customer         \N       0
653                      -73.999979   17080    Customer         \N       0
954                      -73.999061   17967    Customer         \N       0
...                             ...     ...         ...        ...     ...
1016                     -73.980243   19663  Subscriber       1987       2
579                      -73.988021   16638  Subscriber       1976       1
971                      -73.991908   18970  Subscriber       1977       1
1766                     -74.016777   19384    Customer         \N       0
484                      -73.986831   15188  Subscriber       1982       1

[1001958 rows x 14 columns]
ok
month 9
./data/201309-citibike-tripdata.csv
new_file_name ./data/201309-citibike-tripdata.csv

C:\Users\thead\anaconda3\lib\site-packages\numpy\lib\arraysetops.py:569: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)

                        starttime             stoptime  start station id  \
tripduration
1010          2013-09-01 00:00:02  2013-09-01 00:16:52               254
1443          2013-09-01 00:00:09  2013-09-01 00:24:12               151
1387          2013-09-01 00:00:16  2013-09-01 00:23:23               352
405           2013-09-01 00:00:18  2013-09-01 00:07:03               490
270           2013-09-01 00:00:20  2013-09-01 00:04:50               236
...                           ...                  ...               ...
93            2013-09-30 23:59:16  2013-10-01 00:00:49               360
363           2013-09-30 23:59:21  2013-10-01 00:05:24              2003
562           2013-09-30 23:59:30  2013-10-01 00:08:52               293
1237          2013-09-30 23:59:40  2013-10-01 00:20:17               478
1292          2013-09-30 23:59:53  2013-10-01 00:21:25               363

                    start station name  start station latitude  \
tripduration
1010                   W 11 St & 6 Ave               40.735324
1443          Cleveland Pl & Spring St               40.721816
1387                   W 56 St & 6 Ave               40.763406
405                    8 Ave & W 33 St               40.751551
270                St Marks Pl & 2 Ave               40.728419
...                                ...                     ...
93                William St & Pine St               40.707179
363                    1 Ave & E 18 St               40.734161
562              Lafayette St & E 8 St               40.730287
1237                  11 Ave & W 41 St               40.760301
1292                    West Thames St               40.708347

              start station longitude  end station id  \
tripduration
1010                       -73.998004             147
1443                       -73.997203             497
1387                       -73.977225             405
405                        -73.993934             459
270                        -73.987140             393
...                               ...             ...
93                         -74.008873             195
363                        -73.980243             459
562                        -73.990765             463
1237                       -73.998842             318
1292                       -74.017134             363

                           end station name  end station latitude  \
tripduration
1010               Greenwich St & Warren St             40.715422
1443                     E 17 St & Broadway             40.737050
1387          Washington St & Gansevoort St             40.739323
405                        W 20 St & 11 Ave             40.746745
270                       E 5 St & Avenue C             40.722992
...                                     ...                   ...
93                    Liberty St & Broadway             40.709056
363                        W 20 St & 11 Ave             40.746745
562                         9 Ave & W 16 St             40.742065
1237               E 43 St & Vanderbilt Ave             40.753202
1292                         West Thames St             40.708347

              end station longitude  bikeid    usertype birth year  gender
tripduration
1010                     -74.011220   15014  Subscriber       1974       1
1443                     -73.990093   19393    Customer         \N       0
1387                     -74.008119   16160  Subscriber       1992       1
405                      -74.007756   14997  Subscriber       1973       1
270                      -73.979955   19609  Subscriber       1984       1
...                             ...     ...         ...        ...     ...
93                       -74.010434   20594  Subscriber       1989       1
363                      -74.007756   15213    Customer         \N       0
562                      -74.004432   17938  Subscriber       1967       1
1237                     -73.977987   15931    Customer         \N       0
1292                     -74.017134   14826    Customer         \N       0

[1034359 rows x 14 columns]
ok
month 10
./data/201310-citibike-tripdata.csv
new_file_name ./data/201310-citibike-tripdata.csv

C:\Users\thead\anaconda3\lib\site-packages\numpy\lib\arraysetops.py:569: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)

                        starttime             stoptime  start station id  \
tripduration
326           2013-10-01 00:01:08  2013-10-01 00:06:34               239
729           2013-10-01 00:01:21  2013-10-01 00:13:30               322
520           2013-10-01 00:01:24  2013-10-01 00:10:04               174
281           2013-10-01 00:01:25  2013-10-01 00:06:06               430
196           2013-10-01 00:01:27  2013-10-01 00:04:43               403
...                           ...                  ...               ...
534           2013-10-31 23:58:50  2013-11-01 00:07:44               216
416           2013-10-31 23:59:12  2013-11-01 00:06:08               368
404           2013-10-31 23:59:27  2013-11-01 00:06:11               456
651           2013-10-31 23:59:51  2013-11-01 00:10:42               377
332           2013-10-31 23:59:57  2013-11-01 00:05:29               250

                           start station name  start station latitude  \
tripduration
326                  Willoughby St & Fleet St               40.691966
729                   Clinton St & Tillary St               40.696192
520                           E 25 St & 1 Ave               40.738177
281                          York St & Jay St               40.701485
196                            E 2 St & 2 Ave               40.725029
...                                       ...                     ...
534           Columbia Heights & Cranberry St               40.700379
416                        Carmine St & 6 Ave               40.730386
404                     E 53 St & Madison Ave               40.759711
651                          6 Ave & Canal St               40.722438
332                  Lafayette St & Jersey St               40.724561

              start station longitude  end station id  \
tripduration
326                        -73.981302             366
729                        -73.991218             398
520                        -73.977387             403
281                        -73.986569             323
196                        -73.990697             401
...                               ...             ...
534                        -73.995481             398
416                        -74.002150             335
404                        -73.974023             509
651                        -74.005664             463
332                        -73.995653             368

                         end station name  end station latitude  \
tripduration
326              Clinton Ave & Myrtle Ave             40.693261
729              Atlantic Ave & Furman St             40.691652
520                        E 2 St & 2 Ave             40.725029
281           Lawrence St & Willoughby St             40.692362
196               Allen St & Rivington St             40.720196
...                                   ...                   ...
534              Atlantic Ave & Furman St             40.691652
416              Washington Pl & Broadway             40.729039
404                       9 Ave & W 22 St             40.745497
651                       9 Ave & W 16 St             40.742065
332                    Carmine St & 6 Ave             40.730386

              end station longitude  bikeid    usertype birth year  gender
tripduration
326                      -73.968896   16052  Subscriber       1982       1
729                      -73.999979   19412    Customer         \N       0
520                      -73.990697   19645  Subscriber       1984       1
281                      -73.986317   16992  Subscriber       1985       1
196                      -73.989978   15690  Subscriber       1986       1
...                             ...     ...         ...        ...     ...
534                      -73.999979   17905  Subscriber       1990       1
416                      -73.994046   17879  Subscriber       1994       1
404                      -74.001971   17082  Subscriber       1966       1
651                      -74.004432   15587  Subscriber       1970       1
332                      -74.002150   15754  Subscriber       1984       1

[1037712 rows x 14 columns]
ok
month 11
./data/201311-citibike-tripdata.csv
new_file_name ./data/201311-citibike-tripdata.csv
                        starttime             stoptime  start station id  \
tripduration
504           2013-11-01 00:00:17  2013-11-01 00:08:41               326
747           2013-11-01 00:00:20  2013-11-01 00:12:47               375
1005          2013-11-01 00:00:30  2013-11-01 00:17:15               264
622           2013-11-01 00:01:29  2013-11-01 00:11:51               472
1454          2013-11-01 00:01:37  2013-11-01 00:25:51               293
...                           ...                  ...               ...
784           2013-11-30 23:58:38  2013-12-01 00:11:42               546
1034          2013-11-30 23:58:47  2013-12-01 00:16:01               297
1075          2013-11-30 23:59:17  2013-12-01 00:17:12               401
459           2013-11-30 23:59:21  2013-12-01 00:07:00               151
791           2013-11-30 23:59:52  2013-12-01 00:13:03               508

                    start station name  start station latitude  \
tripduration
504                    E 11 St & 1 Ave               40.729538
747            Mercer St & Bleecker St               40.726795
1005              Maiden Ln & Pearl St               40.707065
622                 E 32 St & Park Ave               40.745712
1454             Lafayette St & E 8 St               40.730287
...                                ...                     ...
784               E 30 St & Park Ave S               40.744449
1034                   E 15 St & 3 Ave               40.734232
1075           Allen St & Rivington St               40.720196
459           Cleveland Pl & Spring St               40.721816
791                   W 46 St & 11 Ave               40.763414

              start station longitude  end station id  \
tripduration
504                        -73.984267             349
747                        -73.996951             504
1005                       -74.007319             265
622                        -73.981948             174
1454                       -73.990765             490
...                               ...             ...
784                        -73.983035             404
1034                       -73.986923             284
1075                       -73.989978             476
459                        -73.997203             355
791                        -73.996674             116

                      end station name  end station latitude  \
tripduration
504            Rivington St & Ridge St             40.718502
747                    1 Ave & E 15 St             40.732219
1005          Stanton St & Chrystie St             40.722293
622                    E 25 St & 1 Ave             40.738177
1454                   8 Ave & W 33 St             40.751551
...                                ...                   ...
784                    9 Ave & W 14 St             40.740583
1034             Greenwich Ave & 8 Ave             40.739017
1075                   E 31 St & 3 Ave             40.743943
459              Bayard St & Baxter St             40.716021
791                    W 17 St & 8 Ave             40.741776

              end station longitude  bikeid    usertype birth year  gender
tripduration
504                      -73.983299   16393  Subscriber       1983       2
747                      -73.981656   18244  Subscriber       1971       1
1005                     -73.991475   14636    Customer         \N       0
622                      -73.977387   16685  Subscriber       1980       1
1454                     -73.993934   18055  Subscriber       1975       2
...                             ...     ...         ...        ...     ...
784                      -74.005509   18608  Subscriber       1970       1
1034                     -74.002638   14728  Subscriber       1980       1
1075                     -73.979661   16217  Subscriber       1977       1
459                      -73.999744   15016  Subscriber       1959       1
791                      -74.001497   19376  Subscriber       1965       1

[675774 rows x 14 columns]
ok

month 12
./data/201312-citibike-tripdata.csv
new_file_name ./data/201312-citibike-tripdata.csv
                        starttime             stoptime  start station id  \
tripduration
1015          2013-12-01 00:00:03  2013-12-01 00:16:58               401
962           2013-12-01 00:00:07  2013-12-01 00:16:09               312
768           2013-12-01 00:00:15  2013-12-01 00:13:03               326
218           2013-12-01 00:00:49  2013-12-01 00:04:27              2021
550           2013-12-01 00:01:28  2013-12-01 00:10:38               439
...                           ...                  ...               ...
1014          2013-12-31 23:55:56  2014-01-01 00:12:50               350
682           2013-12-31 23:57:04  2014-01-01 00:08:26               538
1520          2013-12-31 23:57:44  2014-01-01 00:23:04               281
1166          2013-12-31 23:58:14  2014-01-01 00:17:40               492
677           2013-12-31 23:58:16  2014-01-01 00:09:33               463

                             start station name  start station latitude  \
tripduration
1015                    Allen St & Rivington St               40.720196
962                     Allen St & E Houston St               40.722055
768                             E 11 St & 1 Ave               40.729538
218                             W 45 St & 8 Ave               40.759291
550                              E 4 St & 2 Ave               40.726281
...                                         ...                     ...
1014                      Clinton St & Grand St               40.715595
682                             W 49 St & 5 Ave               40.757952
1520          Grand Army Plaza & Central Park S               40.764397
1166                            W 33 St & 7 Ave               40.750200
677                             9 Ave & W 16 St               40.742065

              start station longitude  end station id  \
tripduration
1015                       -73.989978             476
962                        -73.989111             223
768                        -73.984267             291
218                        -73.988597             447
550                        -73.989780             296
...                               ...             ...
1014                       -73.987030             532
682                        -73.977876            2006
1520                       -73.973715             411
1166                       -73.990931             253
677                        -74.004432             448

                        end station name  end station latitude  \
tripduration
1015                     E 31 St & 3 Ave             40.743943
962                      W 13 St & 7 Ave             40.737815
768           Madison St & Montgomery St             40.713126
218                      8 Ave & W 52 St             40.763707
550                 Division St & Bowery             40.714131
...                                  ...                   ...
1014                     S 5 Pl & S 4 St             40.710451
682               Central Park S & 6 Ave             40.765909
1520                   E 6 St & Avenue D             40.722281
1166                     W 13 St & 5 Ave             40.735439
677                     W 37 St & 10 Ave             40.756604

              end station longitude  bikeid    usertype birth year  gender
tripduration
1015                     -73.979661   14729  Subscriber       1979       2
962                      -73.999947   17871  Subscriber       1970       2
768                      -73.984844   18508  Subscriber       1982       2
218                      -73.985162   17745  Subscriber       1976       1
550                      -73.997047   16947  Subscriber       1983       1
...                             ...     ...         ...        ...     ...
1014                     -73.960876   16336  Subscriber       1973       1
682                      -73.976342   18352  Subscriber       1986       1
1520                     -73.976687   15000  Subscriber       1985       1
1166                     -73.994539   21022  Subscriber       1955       1
677                      -73.997901   17559  Subscriber       1986       1

[443966 rows x 14 columns]
ok
writing file

PermissionError: [Errno 13] Permission denied: './data/2013-citi-data.csv'

In [34]:
year_df.head()

,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
tripduration,,,,,,,,,,,,,,
695,2013-06-01 00:00:01,2013-06-01 00:11:36,444,Broadway & W 24 St,40.742354,-73.989151,434.0,9 Ave & W 18 St,40.743174,-74.003664,19678,Subscriber,1983,1
693,2013-06-01 00:00:08,2013-06-01 00:11:41,444,Broadway & W 24 St,40.742354,-73.989151,434.0,9 Ave & W 18 St,40.743174,-74.003664,16649,Subscriber,1984,1
2059,2013-06-01 00:00:44,2013-06-01 00:35:03,406,Hicks St & Montague St,40.695128,-73.995951,406.0,Hicks St & Montague St,40.695128,-73.995951,19599,Customer,NaN,0
123,2013-06-01 00:01:04,2013-06-01 00:03:07,475,E 15 St & Irving Pl,40.735243,-73.987586,262.0,Washington Park,40.691782,-73.973730,16352,Subscriber,1960,1
1521,2013-06-01 00:01:22,2013-06-01 00:26:43,2008,Little West St & 1 Pl,40.705693,-74.016777,310.0,State St & Smith St,40.689269,-73.989129,15567,Subscriber,1983,1

In [35]:
year_df.tail()

,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
tripduration,,,,,,,,,,,,,,
1014,2013-12-31 23:55:56,2014-01-01 00:12:50,350,Clinton St & Grand St,40.715595,-73.987030,532.0,S 5 Pl & S 4 St,40.710451,-73.960876,16336,Subscriber,1973,1
682,2013-12-31 23:57:04,2014-01-01 00:08:26,538,W 49 St & 5 Ave,40.757952,-73.977876,2006.0,Central Park S & 6 Ave,40.765909,-73.976342,18352,Subscriber,1986,1
1520,2013-12-31 23:57:44,2014-01-01 00:23:04,281,Grand Army Plaza & Central Park S,40.764397,-73.973715,411.0,E 6 St & Avenue D,40.722281,-73.976687,15000,Subscriber,1985,1
1166,2013-12-31 23:58:14,2014-01-01 00:17:40,492,W 33 St & 7 Ave,40.750200,-73.990931,253.0,W 13 St & 5 Ave,40.735439,-73.994539,21022,Subscriber,1955,1
677,2013-12-31 23:58:16,2014-01-01 00:09:33,463,9 Ave & W 16 St,40.742065,-74.004432,448.0,W 37 St & 10 Ave,40.756604,-73.997901,17559,Subscriber,1986,1

In [36]:
year_df

,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
tripduration,,,,,,,,,,,,,,
695,2013-06-01 00:00:01,2013-06-01 00:11:36,444,Broadway & W 24 St,40.742354,-73.989151,434.0,9 Ave & W 18 St,40.743174,-74.003664,19678,Subscriber,1983,1
693,2013-06-01 00:00:08,2013-06-01 00:11:41,444,Broadway & W 24 St,40.742354,-73.989151,434.0,9 Ave & W 18 St,40.743174,-74.003664,16649,Subscriber,1984,1
2059,2013-06-01 00:00:44,2013-06-01 00:35:03,406,Hicks St & Montague St,40.695128,-73.995951,406.0,Hicks St & Montague St,40.695128,-73.995951,19599,Customer,NaN,0
123,2013-06-01 00:01:04,2013-06-01 00:03:07,475,E 15 St & Irving Pl,40.735243,-73.987586,262.0,Washington Park,40.691782,-73.973730,16352,Subscriber,1960,1
1521,2013-06-01 00:01:22,2013-06-01 00:26:43,2008,Little West St & 1 Pl,40.705693,-74.016777,310.0,State St & Smith St,40.689269,-73.989129,15567,Subscriber,1983,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1014,2013-12-31 23:55:56,2014-01-01 00:12:50,350,Clinton St & Grand St,40.715595,-73.987030,532.0,S 5 Pl & S 4 St,40.710451,-73.960876,16336,Subscriber,1973,1
682,2013-12-31 23:57:04,2014-01-01 00:08:26,538,W 49 St & 5 Ave,40.757952,-73.977876,2006.0,Central Park S & 6 Ave,40.765909,-73.976342,18352,Subscriber,1986,1
1520,2013-12-31 23:57:44,2014-01-01 00:23:04,281,Grand Army Plaza & Central Park S,40.764397,-73.973715,411.0,E 6 St & Avenue D,40.722281,-73.976687,15000,Subscriber,1985,1
1166,2013-12-31 23:58:14,2014-01-01 00:17:40,492,W 33 St & 7 Ave,40.750200,-73.990931,253.0,W 13 St & 5 Ave,40.735439,-73.994539,21022,Subscriber,1955,1
677,2013-12-31 23:58:16,2014-01-01 00:09:33,463,9 Ave & W 16 St,40.742065,-74.004432,448.0,W 37 St & 10 Ave,40.756604,-73.997901,17559,Subscriber,1986,1

In [47]:
#some of the columns have trip duration then it goes away.  Some of the  data has the right data organization but
#the columns have different names

In [33]:
Columns: [starttime, stoptime, start station id, start station name, start station latitude, start station longitude, end station id, end station name, end station latitude, end station longitude, bikeid, usertype, birth year, gender]

SyntaxError: invalid syntax (<ipython-input-33-b375ec38fc7f>, line 1)